version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: io_team_b_backend
    command: npm run start
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - app-network
  mongo:
    container_name: io_team_b_mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
    container_name: io_team_b_frontend
    command: npm run start
    links:
      - backend
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
